version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.s
    ports:
      - "8080:8080"
    image: fa-code/quote_srv:latest
    restart: "no"

  client:
    build:
      context: .
      dockerfile: Dockerfile.c
    image: fa-code/quote_c:latest
    restart: "no"
    depends_on:
      - server